image: gitpod/workspace-full

tasks:
  - before: sdk install java 17.0.4.1-tem < /dev/null
    init: ./mvnw clean install -Pproduction
    command: ./mvnw spring-boot:run
    name: Run Vaadin Hybrid app

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack